import {
  CASE_PACKAGE_V01_EVIDENCE_RATINGS,
  CASE_PACKAGE_V01_RECOMMENDED_ACTIONS,
  CASE_PACKAGE_V01_SCHEMA_VERSION,
  CASE_PACKAGE_V01_VERDICTS,
  type CasePackageV01,
} from "@/lib/types";

export const minimalSyntheticCasePackageV01 = {
  schema_version: CASE_PACKAGE_V01_SCHEMA_VERSION,
  package_id: "pkg-synthetic-cloudtrail-iam-001",
  created_at: "2026-06-20T12:00:00.000Z",
  package_revision: "r1",
  case: {
    case_id: "case-synthetic-iam-001",
    title: "Synthetic IAM role provisioning review",
    summary:
      "A safe synthetic CloudTrail-style cluster where the generated label may overclaim suspicious intent.",
    reviewable_status: "synthetic_demo",
    review_intent: "validate_label",
    limitations: ["Synthetic fixture; not evidence of real ACME4 or Toponymy support."],
  },
  dataset: {
    dataset_id: "dataset-synthetic-cloudtrail-workshop",
    dataset_name: "Synthetic CloudTrail Workshop Pack",
    dataset_type: "cloudtrail",
    data_classification: "synthetic",
    source_environment: "local-fixture",
    approved_use: "Contract and review-flow testing with safe synthetic data.",
    limitations: ["No raw restricted telemetry is included."],
  },
  cluster: {
    cluster_id: "cluster-iam-029",
    cluster_name: "IAM role provisioning region",
    upstream_cluster_label: "Suspicious IAM privilege escalation",
    cluster_size: 126,
    embedding_map: {
      map_id: "synthetic-map-001",
      map_tool: "datamapplot-adjacent-fixture",
      coordinate_space: "synthetic-2d",
      coordinates: { x: 0.18, y: 0.62 },
    },
    time_range: {
      start_at: "2026-06-12T03:48:00.000Z",
      end_at: "2026-06-12T15:05:00.000Z",
      timezone: "UTC",
    },
    cluster_method: {
      method: "synthetic-hdbscan-style-clustering",
      distance_metric: "cosine",
      parameters: { min_cluster_size: 25 },
    },
  },
  pipeline: {
    pipeline_id: "pipeline-synthetic-package-generator",
    run_id: "run-synthetic-2026-06-20",
    upstream_tool: "synthetic-demo-package-generator",
    pipeline_version: "0.1.0",
    embedding_model: "synthetic-embedding-fixture",
    clustering_method: "synthetic-hdbscan-style-clustering",
    dimensionality_reduction_method: "datamapplot-adjacent-2d-projection",
    naming_model: "synthetic-baseline-labeler",
    prompt: {
      prompt_id: "prompt-synthetic-labeler-v1",
      prompt_summary: "Generate a concise cluster label from sanitized summaries.",
    },
    generated_at: "2026-06-20T11:58:00.000Z",
    config_summary: "Synthetic package generated for CasePackage v0.1 type coverage.",
  },
  candidate_labels: [
    {
      label_id: "label-ai-suspicious-iam",
      label: "Suspicious IAM privilege escalation",
      source: "ai_generated",
      model_reference: "synthetic-baseline-labeler",
      prompt_reference: "prompt-synthetic-labeler-v1",
      run_id: "run-synthetic-2026-06-20",
      confidence: {
        status: "available",
        value: 0.61,
        min: 0,
        max: 1,
        interpretation: "higher_is_better",
      },
      rank: 1,
      linked_claim_ids: ["claim-role-changes", "claim-suspicious-intent"],
    },
    {
      label_id: "label-human-routine-provisioning",
      label: "Routine IAM role provisioning",
      source: "human_baseline",
      confidence: {
        status: "unavailable",
        reason: "Human baseline label is not model-scored.",
      },
      rank: 2,
      linked_claim_ids: ["claim-role-changes", "claim-planned-rollout"],
    },
  ],
  claims: [
    {
      claim_id: "claim-role-changes",
      text: "The cluster contains role creation and policy attachment activity.",
      claim_type: "behavioral_summary",
      linked_evidence_ids: ["evidence-role-lifecycle", "evidence-rollout-metadata"],
      linked_label_ids: ["label-ai-suspicious-iam", "label-human-routine-provisioning"],
      confidence: {
        status: "available",
        value: 0.92,
        min: 0,
        max: 1,
        interpretation: "higher_is_better",
      },
    },
    {
      claim_id: "claim-suspicious-intent",
      text: "The cluster proves suspicious or malicious privilege escalation.",
      claim_type: "intent",
      linked_evidence_ids: ["evidence-no-downstream-abuse"],
      linked_label_ids: ["label-ai-suspicious-iam"],
      caveats: ["Intent is not directly evidenced by the sanitized summaries."],
    },
    {
      claim_id: "claim-planned-rollout",
      text: "The cluster mostly resembles a planned provisioning workflow.",
      claim_type: "cluster_quality",
      linked_evidence_ids: ["evidence-rollout-metadata"],
      linked_label_ids: ["label-human-routine-provisioning"],
      assumptions: ["Rollout metadata is representative of the cluster majority."],
    },
  ],
  evidence_items: [
    {
      evidence_id: "evidence-role-lifecycle",
      title: "Role lifecycle feature stack",
      summary:
        "Sanitized feature summaries include CreateRole, AttachRolePolicy, and TagRole.",
      evidence_type: "salient_feature",
      content: {
        content_type: "structured_summary",
        fields: {
          features: ["CreateRole", "AttachRolePolicy", "TagRole"],
          session_count: 98,
        },
      },
      source_reference: {
        source_id: "source-synthetic-features",
        source_type: "derived_feature_summary",
      },
      provenance_reference: "prov-synthetic-package",
      sanitization_status: "synthetic",
      linked_claim_ids: ["claim-role-changes"],
      weight: {
        status: "available",
        value: 0.88,
        min: 0,
        max: 1,
      },
    },
    {
      evidence_id: "evidence-rollout-metadata",
      title: "Rollout metadata",
      summary: "Most sessions occur during a daytime platform rollout window.",
      evidence_type: "event_summary",
      content: {
        content_type: "text",
        text: "Owner and change-window markers appear in the synthetic summaries.",
      },
      source_reference: {
        source_id: "source-synthetic-rollout",
        source_type: "sanitized_event_summary",
      },
      provenance_reference: "prov-synthetic-package",
      sanitization_status: "synthetic",
      linked_session_ids: ["session-role-created"],
      linked_claim_ids: ["claim-role-changes", "claim-planned-rollout"],
    },
    {
      evidence_id: "evidence-no-downstream-abuse",
      title: "No downstream abuse evidence",
      summary:
        "The synthetic evidence package does not show use of the roles for sensitive access.",
      evidence_type: "analyst_note",
      content: {
        content_type: "text",
        text: "Absence of downstream abuse weakens the suspicious intent claim.",
      },
      source_reference: {
        source_id: "source-synthetic-analyst-note",
        source_type: "analyst_note",
      },
      provenance_reference: "prov-synthetic-package",
      sanitization_status: "synthetic",
      linked_claim_ids: ["claim-suspicious-intent"],
    },
  ],
  evidence_to_claim_mappings: [
    {
      claim_id: "claim-role-changes",
      evidence_id: "evidence-role-lifecycle",
      relationship: "supports",
      expected_support: "supports",
      rationale: "Role lifecycle features directly match the narrow activity claim.",
    },
    {
      claim_id: "claim-suspicious-intent",
      evidence_id: "evidence-no-downstream-abuse",
      relationship: "contradicts",
      expected_support: "contradicts",
      rationale: "The evidence weakens a confident malicious-intent interpretation.",
    },
  ],
  representative_sessions: [
    {
      session_id: "session-role-created",
      title: "Role created for analytics connector",
      summary: "CreateRole, TagRole, and AttachRolePolicy appear with owner metadata.",
      feature_highlights: ["CreateRole", "TagRole", "AttachRolePolicy"],
      safe_reference: {
        reference_id: "ref-session-role-created",
        reference_type: "synthetic_fixture_path",
        uri: "sample/cloudtrail/iam-029/session-role-created",
      },
      cluster_membership: {
        cluster_id: "cluster-iam-029",
        membership_score: {
          status: "available",
          value: 0.91,
          min: 0,
          max: 1,
        },
      },
      flags: ["representative"],
      linked_evidence_ids: ["evidence-role-lifecycle", "evidence-rollout-metadata"],
    },
    {
      session_id: "session-passrole-probe",
      title: "Cross-account PassRole-style probe",
      summary: "PassRole-style access check appears off-hours and lacks rollout tags.",
      feature_highlights: ["iam:PassRole", "off-hours"],
      cluster_membership: {
        cluster_id: "cluster-iam-029",
        membership_score: {
          status: "available",
          value: 0.29,
          min: 0,
          max: 1,
        },
      },
      flags: ["outlier_candidate", "needs_context"],
      linked_evidence_ids: ["evidence-rollout-metadata"],
    },
  ],
  outlier_impostor_candidates: [
    {
      candidate_id: "candidate-passrole-probe",
      session_id: "session-passrole-probe",
      reason: "Low feature overlap and off-hours timing could indicate impurity.",
      score: {
        status: "available",
        value: 0.82,
        min: 0,
        max: 1,
        interpretation: "higher_is_better",
      },
      expected_review_use: "outlier_check",
    },
  ],
  neighbor_clusters: [
    {
      neighbor_cluster_id: "cluster-iam-041",
      label: "Standard platform role lifecycle",
      distance: {
        status: "available",
        value: 0.18,
        min: 0,
        max: 1,
        interpretation: "lower_is_better",
      },
      reason_this_neighbor_matters:
        "It shares role lifecycle features but has clearer change-ticket context.",
      confusion_risk: {
        status: "available",
        value: 0.41,
        min: 0,
        max: 1,
      },
    },
  ],
  metrics: {
    cluster_coherence: {
      status: "available",
      value: 0.74,
      min: 0,
      max: 1,
      interpretation: "higher_is_better",
    },
    evidence_coverage: {
      status: "available",
      value: 0.67,
      min: 0,
      max: 1,
      interpretation: "higher_is_better",
    },
    temporal_stability: {
      status: "unavailable",
      reason: "The synthetic fixture covers one short review window.",
    },
  },
  provenance: {
    provenance_id: "prov-synthetic-package",
    source_system: "synthetic-fixture-generator",
    source_artifact: "local synthetic package fixture",
    generating_tool: "Telemetry Court test fixture",
    generated_at: "2026-06-20T11:58:00.000Z",
    upstream_run_id: "run-synthetic-2026-06-20",
    references: [
      {
        reference_id: "ref-synthetic-source",
        reference_type: "synthetic_fixture_path",
        uri: "lib/casePackageV01Fixture.ts",
      },
    ],
    owner: {
      team: "Telemetry Court",
    },
  },
  sanitization: {
    status: "synthetic",
    method: "Generated safe fixture summaries with no raw restricted telemetry.",
    redaction_notes: ["No real principals, accounts, or events are present."],
    allowed_display_level: "summary_only",
    raw_drilldown_allowed: false,
    safe_reference_type: "synthetic_fixture_path",
  },
  review_configuration: {
    blind_review_enabled: true,
    initially_hidden_label_ids: ["label-ai-suspicious-iam"],
    required_review_stages: [
      "landscape",
      "case_file",
      "blind_review",
      "ai_reveal",
      "evidence_classification",
      "label_comparison",
      "outlier_impostor_review",
      "structured_verdict",
    ],
    allowed_evidence_ratings: [...CASE_PACKAGE_V01_EVIDENCE_RATINGS],
    allowed_verdicts: [...CASE_PACKAGE_V01_VERDICTS],
    allowed_recommended_actions: [...CASE_PACKAGE_V01_RECOMMENDED_ACTIONS],
    required_reviewer_actions: [
      "choose_blind_interpretation",
      "reveal_ai_label",
      "rate_linked_evidence",
      "choose_label_winner",
      "choose_outlier_or_impostor",
      "choose_final_verdict",
      "choose_recommended_action",
    ],
  },
} satisfies CasePackageV01;
